apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: ingress-system
spec:
  interval: 5m
  chart:
    spec:
      chart: haproxy-ingress
      version: ">= 0.14.0"
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
      interval: 10m
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controller:
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi
      kubernetesGateway:
        enabled: true
      extraArgs:
        watch-gateway: ""
