apiVersion: ENC[AES256_GCM,data:S10=,iv:Umf/ZI+GLUsVEDtq/7I7Btn98AOQB9lePfklVO/CKbw=,tag:elZp7IbnbqeK351dGmfdvg==,type:str]
kind: ENC[AES256_GCM,data:Quf3s+06,iv:DUuKqBvISViwfsO/fdyi0lDBTTZ4V2JH0RA2wJycp6E=,tag:Lv5tior7LCLl5ob7hJ/htA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/ferePEEY3Ji248=,iv:SG8F/b12ySy7V7QgNn31ifl9ETFIJX06UIgjwHx0/Ow=,tag:kNFtf4kkshW4XD9yFpJNDQ==,type:str]
    namespace: ENC[AES256_GCM,data:dQH/YgOR9Q==,iv:ooW4Jl2xLJejaMjUjaMsUI0DEQvzzOSxDa48au1Rzp0=,tag:Kpt0ndHKolhFDF1ZLNg6QA==,type:str]
stringData:
    my-password: ENC[AES256_GCM,data:j0B/SlU+JSKl76xVBeDnBM0J,iv:3bqwRwj0NRQ6CMWDXwOZJuM6slt6xBiSCTE0mnGQrwo=,tag:cHo4q/Ps6IFdQ4hb07P4LA==,type:str]
sops:
    age:
        - recipient: age15k2kss4sg0s0d72phtkae4ma92vtv8wavmrjf3zy580m77mdz9wsv2cky7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOXcwMUxCNUJFZFRlc2VO
            TWljd3hJOEF5Q0h1VmovMGxSZ0g0ak9pR1hZCnpZMnFqWHlhZ2QwN3lVK2NUSVNs
            cm5DbkpuYk9pVU4vOXBSN1lqSkJZU2cKLS0tIGtQMkNBdjk5aTZseWZoVVloYkhJ
            d2YrU3FsRGlJOVFWZDVNZ2JRQU8wQzAKRFIBtZiPmLGxhxmtoLJ99G1DCgqotxNr
            lHbM+cPM9BBcga78Fg1rTzZ5fHoEurjE84Y2oCrLTIJFzoA2ZGppew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T04:09:47Z"
    mac: ENC[AES256_GCM,data:mG5NvR2MQbt7A/9oglQV2Eh6nmfWcThUrTU5WZGDwU2fwtw8UZPZpB9n/I8V9up230mDNSrZapyg4pVb4oL2mJqt6jiE+wgApkOnQlTp4zL3b/la8I6vAu0chmHZFICkchYUcGdf3zt7KdYuW8LwYhQ1n25ZRZfoJDeE/gDtt7c=,iv:p1sSZgeYaaSekfQwsR//MPVz4VgnEWgopeDBdDzBA54=,tag:p0dWQZpEVNt5btz9RV5fgw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
