---
apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: default
stringData:
    my-password: ENC[AES256_GCM,data:xhmPukb9hM6sI6/2OZiMF8Is,iv:1VG8Li6im5pWslFKMc4RlKCO1gh1PR68uUtDbdfyxsY=,tag:0g/s1f8tOiiENPqrEwvtgg==,type:str]
sops:
    age:
        - recipient: age15k2kss4sg0s0d72phtkae4ma92vtv8wavmrjf3zy580m77mdz9wsv2cky7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhM0dTRHl5dHd0UXpuNDBD
            NlpZUEg1b1pOV0JrTzJkcTBSRXM1dEtPaWh3CmJ6dmY2RHNaMVVPU3gxd3ljY1Z4
            clJBZ0dBSzJuSHRnSEFmYWo3OFZKckEKLS0tIFk4SGUvbHZJYVA4aGtaVTJCMXVx
            NFRObjBEVUJ5ZDc5K3lCbEo0eVRZaVkK6wjKNgoWITKJCCf0cinyzUsM5N+/SbNw
            A8/gPvewNaPvqC5iehoWDYegbB3jEhxrWzamm8zVsbBi3sbkWswhCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T04:10:50Z"
    mac: ENC[AES256_GCM,data:tp7mS6Kbh9Pd9CKxB31+4LklOfpaNoZ3G5pQGBo463TCBahHkrM1sQwFbQfSlCOiuxxLEG3xfklHo2Eb9NXoFqD4SKhr5dWQxNmBH/iWC0uoVBOkO8gpM2+EL8bDMZiJGCUkTPWNH/78hkP3qCQSNpTCFjJ/os0mOOp1jEXSdoU=,iv:luJHhFXhAEs+nWS4royYOkgcfhXJ/nphbDUfEy9M0hk=,tag:8oavcq3ojC04yU3LuKciRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
