apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">= 50.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 10m
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    prometheus:
      prometheusSpec:
        retention: 1d
        replicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
    alertmanager:
      alertmanagerSpec:
        replicas: 1
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 128Mi
    grafana:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      additionalDataSources:
        - name: Loki
          type: loki
          uid: loki
          url: http://loki.monitoring.svc.cluster.local:3100
          access: proxy
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: "default"
              orgId: 1
              folder: ""
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          cert-manager:
            gnetId: 11001
            revision: 1
            datasource: Prometheus
          blackbox-exporter:
            gnetId: 13659
            revision: 2
            datasource: Prometheus
          haproxy-ingress:
            gnetId: 12056
            revision: 1
            datasource: Prometheus
          loki:
            gnetId: 13639
            revision: 2
            datasource: Loki
