---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/prometheus
  - ../base/grafana-alloy
  - ../base/haproxy-ingress
  - ../base/loki
  - ../base/blackbox-exporter
  - ../base/gateway-api
  - ../base/cert-manager
  - ../base/test-secret.yaml
